name: Run Scripts

on:
  push:
    branches:
      - master

jobs:
  run-scripts:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    
    - name: Install Node.js dependencies
      run: npm install

    - name: Install AWS CLI
      run: sudo apt-get install awscli -y

    - name: Configure AWS CLI
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set region ${{ secrets.AWS_REGION }}

    - name: Run calc_position.js
      run: node calc_position.js Tile-54-26-1-1.zip

    - name: Run tiles.sh
      run: bash tiles.sh

    - name: Run blender_script.py
      run: python3 blender_script.py

    - name: Run test.sh
      run: bash test.sh
